CREATE TABLE IF NOT EXISTS person(
                        id BIGINT generated by default as identity primary key,
                        mail varchar UNIQUE NOT NULL,
                        password varchar NOT NULL,
                        role varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS task(
                     id BIGINT generated by default as identity primary key,
                     header varchar NOT NULL,
                     description varchar NOT NULL,
                     status varchar DEFAULT 'PENDING' NOT NULL,
                     priority varchar DEFAULT 'MEDIUM' NOT NULL,
                     author_id bigint NOT NULL,
                     implementer_id bigint NOT NULL,
                     FOREIGN KEY (author_id) REFERENCES person(id) ON DELETE CASCADE ON UPDATE CASCADE,
                     FOREIGN KEY (implementer_id) REFERENCES person(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS comment(
                        id BIGINT generated by default as identity primary key,
                        text varchar NOT NULL,
                        person_id BIGINT NOT NULL,
                        task_id BIGINT NOT NULL,
                        FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE ON UPDATE CASCADE,
                        FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE ON UPDATE CASCADE
);


INSERT INTO person (mail, password, role) VALUES
                                              ('admin@example.com', '$2a$12$WWc1Ae5A50BzcMe1l7AlFe9xBjnjWl.e5zGvCLlBFx505Aw91NO86', 'ROLE_ADMIN'),
                                              ('user1@example.com', '$2a$12$i0mdFR1qAw1nu37Kt6hoY..7KJOVpy.A4xrRhBsHiFtWYSs7CuA9a', 'ROLE_USER'),
                                              ('user2@example.com', '$2a$12$NZfCoL39lXFh9zDVqAMyK.nUhHG3eI9Fh/n/1EpeIkcSRxR1.FcKG', 'ROLE_USER');

INSERT INTO task (header, description, status, priority, author_id, implementer_id) VALUES
                                                                                        ('Создать презентацию', 'Создать презентацию для совещания', 'PENDING', 'HIGH', 1, 2),
                                                                                        ('Обновить сайт', 'Обновить главную страницу сайта', 'IN_PROGRESS', 'MEDIUM',1, 3),
                                                                                        ('Подготовить отчет', 'Подготовить месячный отчет по продажам', 'IN_PROGRESS', 'HIGH', 1, 2),
                                                                                        ('Исправить баги', 'Исправить найденные ошибки в системе', 'COMPLETED', 'LOW', 1, 2),
                                                                                        ('Запустить рекламную кампанию', 'Запустить новую рекламную кампанию', 'PENDING', 'MEDIUM', 1, 1);
INSERT INTO comment (text, person_id, task_id) VALUES
                                                   ('Нужно доработать презентацию, добавить больше информации.', 2, 1),
                                                   ('Внес изменения в дизайн сайта, требуется ревизия.', 3, 2),
                                                   ('Презентация готова, можно отправить на утверждение.', 2, 1),
                                                   ('Страница сайта обновлена, не забыть проверить мобильную версию.', 3, 2),
                                                   ('Отчет почти готов, требуется еще несколько данных по продажам.', 2, 3),
                                                   ('Задача завершена, баги исправлены.', 2, 4),
                                                   ('Кампания запущена, ожидаем результаты.', 1, 5),
                                                   ('Презентация нуждается в доработке, требуется добавить графики.', 1, 1),
                                                   ('Сайт обновлен, нужно выполнить проверку всех ссылок.', 1, 2),
                                                   ('Отчет завершен, ожидаем отзывы от руководства.', 2, 3);
