networks:
  dev:
    name: dev


services:

  taskManagerDb:
    image: postgres:16
    container_name: taskManager-db
    environment:
      - POSTGRES_DB=taskManagerDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1212
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - dev

  backend:
    build:
      context: .
    depends_on:
      - taskManagerDb

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskManager-db:5432/taskManagerDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1212
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - dev
    ports:
      - "8080:8080"


volumes:
  postgres_data: